"""Place search for the web UI.

Two providers behind one interface:

  * Google Places (New), when `google_maps_api_key` is set. Autocomplete returns
    place ids without coordinates; `resolve()` fetches the location on selection
    (a cheaper SKU than asking for it up front on every keystroke). A session
    token generated by the browser ties the keystrokes and the selection together
    for billing.
  * Photon (OSM), otherwise and as the fallback when Google fails. Results carry
    coordinates immediately. Photon also does reverse geocoding.

Proxied through the API rather than called from the browser so results are
cached, the provider can be swapped by changing config, and a Google Maps
authorisation failure in the browser cannot break search. Queries are biased to
Québec City and clipped to its bounding box: "Laval" must mean Université Laval,
not the city near Montréal.
"""

from __future__ import annotations

import logging
from collections import OrderedDict
from dataclasses import dataclass
from typing import Any

import httpx

from avelo.config import Settings, get_settings

log = logging.getLogger(__name__)

_CACHE_SIZE = 2048


@dataclass(frozen=True)
class Place:
    name: str
    label: str  # one-line description: street, district, city
    lat: float | None
    lon: float | None
    kind: str  # OSM value or Google primary type, e.g. "university"
    place_id: str | None = None  # Google place id when the location is not yet known
    provider: str = "osm"


class GeocodeError(RuntimeError):
    """Upstream geocoder unreachable or malformed."""


class Geocoder:
    def __init__(
        self, settings: Settings | None = None, client: httpx.AsyncClient | None = None
    ) -> None:
        self.settings = settings or get_settings()
        self._client = client or httpx.AsyncClient(
            timeout=self.settings.http_timeout_seconds,
            headers={"User-Agent": "avelo-route-optimizer/1.0"},
        )
        self._owns_client = client is None
        self._cache: OrderedDict[str, list[Place]] = OrderedDict()
        self._google_ok = bool(self.settings.google_maps_api_key)

    async def aclose(self) -> None:
        if self._owns_client:
            await self._client.aclose()

    @property
    def provider(self) -> str:
        return "google" if self._google_ok else "osm"

    # -- cache ----------------------------------------------------------------

    def _remember(self, key: str, places: list[Place]) -> list[Place]:
        self._cache[key] = places
        if len(self._cache) > _CACHE_SIZE:
            self._cache.popitem(last=False)
        return places

    # -- Google Places (New) --------------------------------------------------

    def _bbox(self) -> tuple[float, float, float, float]:
        lon0, lat0, lon1, lat1 = (float(x) for x in self.settings.geocoder_bbox.split(","))
        return lat0, lon0, lat1, lon1

    async def _google_search(
        self, q: str, limit: int, lang: str, session: str | None
    ) -> list[Place]:
        lat0, lon0, lat1, lon1 = self._bbox()
        body: dict[str, Any] = {
            "input": q,
            "languageCode": "fr-CA" if lang == "fr" else "en-CA",
            "regionCode": "ca",
            "locationRestriction": {
                "rectangle": {
                    "low": {"latitude": lat0, "longitude": lon0},
                    "high": {"latitude": lat1, "longitude": lon1},
                }
            },
            "origin": {
                "latitude": self.settings.geocoder_bias_lat,
                "longitude": self.settings.geocoder_bias_lon,
            },
        }
        if session:
            body["sessionToken"] = session
        r = await self._client.post(
            f"{self.settings.google_places_url}/places:autocomplete",
            json=body,
            headers={"X-Goog-Api-Key": self.settings.google_maps_api_key},
        )
        r.raise_for_status()
        out: list[Place] = []
        for s in r.json().get("suggestions", [])[:limit]:
            p = s.get("placePrediction")
            if not p:
                continue
            fmt = p.get("structuredFormat", {})
            name = fmt.get("mainText", {}).get("text") or p.get("text", {}).get("text")
            if not name or not p.get("placeId"):
                continue
            types = p.get("types", [])
            out.append(
                Place(
                    name=str(name),
                    label=str(fmt.get("secondaryText", {}).get("text", "")),
                    lat=None,
                    lon=None,
                    kind=str(types[0]) if types else "",
                    place_id=str(p["placeId"]),
                    provider="google",
                )
            )
        return out

    async def resolve(self, place_id: str, session: str | None = None) -> Place | None:
        """Location of a Google place id (the Place Details "Location Only" SKU)."""
        if not self._google_ok:
            return None
        params: dict[str, str] = {"fields": "location,displayName,formattedAddress,primaryType"}
        if session:
            params["sessionToken"] = session
        try:
            r = await self._client.get(
                f"{self.settings.google_places_url}/places/{place_id}",
                params=params,
                headers={"X-Goog-Api-Key": self.settings.google_maps_api_key},
            )
            r.raise_for_status()
            d = r.json()
            loc = d.get("location", {})
            return Place(
                name=str(d.get("displayName", {}).get("text", "")),
                label=str(d.get("formattedAddress", "")),
                lat=float(loc["latitude"]),
                lon=float(loc["longitude"]),
                kind=str(d.get("primaryType", "")),
                place_id=place_id,
                provider="google",
            )
        except (httpx.HTTPError, KeyError, ValueError, TypeError) as exc:
            raise GeocodeError(f"place lookup failed: {exc}") from exc

    # -- Photon (OSM) ---------------------------------------------------------

    @staticmethod
    def _label(props: dict[str, Any]) -> str:
        parts = [
            " ".join(str(p) for p in (props.get("housenumber"), props.get("street")) if p),
            props.get("district"),
            props.get("city"),
        ]
        seen: list[str] = []
        for part in parts:
            if part and part not in seen and part != props.get("name"):
                seen.append(str(part))
        return ", ".join(seen)

    async def _photon_search(self, q: str, limit: int, lang: str) -> list[Place]:
        params: dict[str, str | int | float] = {
            "q": q,
            "limit": limit,
            "lang": lang,
            "lat": self.settings.geocoder_bias_lat,
            "lon": self.settings.geocoder_bias_lon,
            "bbox": self.settings.geocoder_bbox,
        }
        r = await self._client.get(self.settings.geocoder_url, params=params)
        r.raise_for_status()
        places: list[Place] = []
        for f in r.json().get("features", []):
            props = f.get("properties", {})
            coords = f.get("geometry", {}).get("coordinates")
            name = props.get("name") or props.get("street")
            if not coords or not name:
                continue
            places.append(
                Place(
                    name=str(name),
                    label=self._label(props),
                    lat=float(coords[1]),
                    lon=float(coords[0]),
                    kind=str(props.get("osm_value") or props.get("type") or ""),
                )
            )
        return places

    # -- public ---------------------------------------------------------------

    async def search(
        self, query: str, limit: int = 6, lang: str = "fr", session: str | None = None
    ) -> list[Place]:
        q = " ".join(query.split()).lower()
        if len(q) < 2:
            return []
        key = f"{q}|{limit}|{lang}"
        hit = self._cache.get(key)
        if hit is not None:
            self._cache.move_to_end(key)
            return hit

        if self._google_ok:
            try:
                return self._remember(key, await self._google_search(q, limit, lang, session))
            except (httpx.HTTPError, ValueError, TypeError) as exc:
                # Quota, key restriction, outage: fall back for the rest of this process.
                log.warning("Google Places failed (%s); using Photon from now on", exc)
                self._google_ok = False
        try:
            return self._remember(key, await self._photon_search(q, limit, lang))
        except (httpx.HTTPError, ValueError) as exc:
            raise GeocodeError(f"geocoder request failed: {exc}") from exc

    async def reverse(self, lat: float, lon: float, lang: str = "fr") -> Place | None:
        """Nearest named place to a point, for labelling a pin dropped on the map."""
        url = self.settings.geocoder_url.rstrip("/")
        url = url[: -len("/api")] + "/reverse" if url.endswith("/api") else url + "/reverse"
        params: dict[str, str | int | float] = {"lat": lat, "lon": lon, "lang": lang, "limit": 1}
        try:
            r = await self._client.get(url, params=params)
            r.raise_for_status()
            features = r.json().get("features", [])
        except (httpx.HTTPError, ValueError) as exc:
            raise GeocodeError(f"reverse geocode failed: {exc}") from exc
        for f in features:
            props = f.get("properties", {})
            name = props.get("name") or props.get("street")
            if name:
                return Place(
                    name=str(name),
                    label=self._label(props),
                    lat=lat,
                    lon=lon,
                    kind=str(props.get("osm_value") or ""),
                )
        return None
